### ISSUE TITLE
Is Checkstyle 6.5 a hard requirement or can it be upgraded?

### ISSUE THREAD

**Issue by virtualandy** [bufferapp/android-guidelines#12]
This is purely my ignorance around checkstyle showing, but wasn't sure if there was a specific reason that this uses [checkstyle 6.5](https://github.com/bufferapp/android-guidelines/blob/master/Code_Quality/quality.gradle#L6).

Just curious as I copy this setup over to our own project, if I should dare to upgrade. Or if it's a known thing that anything >6.5 will explode in Android land.

Thanks a ton for sharing this, so far it's been hugely beneficial!

**Comment by hitherejoe** [comment]
Hey! Glad it's been of use to you so far :)

THere's no specific reason to using 6.5, it was just the latest version that was available when originally setup. There's a 7.1 now I think so if compatible with our setup I'll probably upgrade that soon. 

I imagine older versions _should_ work, the only thing I can think of that may be lacking are certain rules maybe? Other than that I would presume it would be fine 🙂 Would be interested to know if this works for you or not!

**Comment by virtualandy** [comment]
@hitherejoe thanks. If I give it a shot and find great success, I'll come back and share. Was hoping there wasn't some big blocker you all had run into, so that's good to know that wasn't the case. :)
