### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by maxim-pandra** [bufferapp/android-guidelines#9]
Hi. Why should i put overriden method like in the code snippet to the beginning? They are almost the same across every activity/fragment class and are not that valuable. What's the point? Help me figure it out. :) 
Thanks for sharing this guidline! gonna use it.

```
    @Override
    protected void injectComponent(MainFragmentComponent component) {
        component.inject(this);
    }

    @Override
    protected int getLayoutId() {
        return R.layout.fragment_create_review;
    }

```

**Comment by hitherejoe** [comment]
Hey! Well, they're nice to have collated in the same place rather than scattered throughout the class. Also they are often related to the lifecycle of the class they are in, so it makes the code of the class easier to follow if they are easily accessible and in-order :)
